# author: 0-8-4
# date： 24-11-2022 18：34 AEDT
#
# This script is used to automatically build docker image and
# push to DockerHub when every new release is published

name: DockerHub CI

on:
  release:
    types: [published]
  push:
  # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

env:
  DOCKERHUB_REPO: hansaes/autman

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ github.ref.replace('refs/tags/', '') }}

