# author: 0-8-4
# date： 24-11-2022 18：34 AEDT
#
# This script is used to automatically build docker image and
# push to DockerHub when every new release is published

name: DockerHub CI

on:
  push:
  # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # release:
  #   types: [published]

  workflow_dispatch:

env:
  DOCKERHUB_REPO: hansaes/autman

jobs:
  build:
    runs-on: centos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        # 将GTIHUB的信息都打印出来，后面的脚本可以使用这些信息，例如后面的镜像TAG用的就是这里面的commitid
        run: echo "Hello ${{ github.event.commits[0].id }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - 
      #   name: Get version
      #   id: get_version
      #   run: | 
      #     echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      #     echo ${{ steps.get_version.outputs.VERSION }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ steps.get_version.outputs.VERSION }}

