name: Docker Image CI

on:
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Release Tag
        run: |
          API_RESPONSE=$(curl -s "https://api.github.com/repos/hdbjlizhe/fanli/releases/latest")
          echo "API Response: $API_RESPONSE"
          TAG_NAME=$(echo "$API_RESPONSE" | grep -oP '"tag_name": "\K.*?(?=")')
          echo "Tag Name: $TAG_NAME"

      - name: Show Variable Value
        run: |
          VARIABLE_VALUE="${{ steps.get-variable.outputs.variable_value }}"
          echo "Setting environment variable MY_VARIABLE to: $VARIABLE_VALUE"
          echo "MY_VARIABLE=$VARIABLE_VALUE" >> $GITHUB_ENV

      - name: Use Variable in Another Step
        run: |
          echo "Accessing MY_VARIABLE: $MY_VARIABLE"
